### ISSUE TITLE
Questions about antibody structure data format

### ISSUE THREAD

**Issue by junhaobearxiong** [piercelab/antibody_benchmark#2]
Hi! I have a few questions regarding the antibody structures in the dataset:

1. As far as I understand, the bound structures are obtained from SAbDab, then the corresponding unbound structures are searched from the PDB. Are the antibody structures in either the bound or unbound conformations already renumbered by one of the numbering systems (e.g. SAbDab has Chothia numbered structures)?
2. In the summary file antibody_antigen_cases.txt, for the "Complex PDB" columns, when there are two antibody chains, are these consistently listed as heavy chain id followed by light chain id? 
 
Thank you for curating such a valuable dataset!

**Comment by junhaobearxiong** [comment]
I realized the answer to the second question is no. Perhaps the chain id information would be helpful to include in the summary table, or at least noted that the information is not currently contained within the dataset?

**Comment by bpierce12** [comment]
Thanks for the questions and your interest in the benchmark. Here are the
answers to your questions:
1. We did not renumber the antibodies for the downloadable PDB files, they
should be in the original numbering from the PDB.
2. Our convention is to have the chain IDs in that order (heavy, light) in
that file, but it seems that there are a few exceptions to that,
specifically for some of the older structures that predated the recent
(Benchmark 5.5) update.

Let me know if you have any more questions.

**Comment by junhaobearxiong** [comment]
Hi! I have a related question: for a given residue in the antigen, are the residue numbers the same in the bound vs. unbound pdb files? If they are not, what would be a good way to match the residues in the bound vs. unbound antigen structures?

**Comment by bpierce12** [comment]
Often the residue numbers are the same between bound and unbound PDBs, but
not always. To find the correspondence between residues, I use BLAST to
align the sequences obtained from the two PDBs, and then use the BLAST
alignment between the chains to go back to the PDBs and match the residues
between the structures. Let me know if you have any more questions.

Best,
Brian
